#
# http://travis-ci.org configuration file for openMVG
#

language: cpp

compiler:
  - gcc
  - clang

before_install:
 - export NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
 
install: sudo apt-get install cmake libpng-dev libjpeg8-dev libxxf86vm1 libxxf86vm1 libxxf86vm-dev x11proto-xf86vidmode-dev libxrandr-dev

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . ../openMVG/src

script:
  - make -j 4
# Perform unit tests only on GCC builds
  - if [ "$CC" = "gcc" ]; then make test; fi

branches:
  only:
    - develop

